# Generated by Django 2.2.4 on 2019-08-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190613_1731'),
        ('mainapp', '0002_auto_20190814_1858'),
    ]

    operations = [
    ]
